logging:
  level:
    ROOT: INFO
    cn.zhxu.bs: DEBUG
    com.goudong: DEBUG
    com.zhy.authentication.server: DEBUG
#    org.apache.tomcat: DEBUG
#    org.apache.tomcat.jdbc.pool: DEBUG

server:
  port: 8080
  servlet:
    context-path: /api/authentication-server
spring:
  main:
    allow-bean-definition-overriding: true #重命名其中一个 bean 或启用覆盖
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false #工程中的资源文件建立映射
  application:
    name: authentication-server #微服务名
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: GMT+8
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/authentication-server?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&createDatabaseIfNotExist=true
    username: root
    password: l(=8gp_04h*&

  redis:
    database: 0   # Redis数据库索引（默认为0）
    host: 127.0.0.1 # Redis服务器地址
    port: 6379
    password: 123456
    timeout: 3000
  ## flyway数据迁移
  flyway:
    #是否开启
    enabled: false
    baseline-version: 0
    baseline-on-migrate: true
    table: flyway_schema_history
knife4j:
  enable: true         # 是否开启Knife4j增强模式，默认值为false
  production: false    # 生产环境开启
  basic:
    enable: true       # BasicHttp功能，默认为false
    username: knife4j  # 用户名
    password: knife4j  # 密码
  setting: # 前端Ui的个性化配置属性
    enableDebug: true  # 启用调试，默认为true 无效

bean-searcher:
  sql:
    default-mapping:
      ignore-fields: org_grails_datastore_gorm_GormValidateable__errors

#goudong:
#  web:
#    api-log:
#      enabled: true

authentication:
  server:
    app:
      adminDefaultPassword: 123456
